#!/usr/bin/env bash
# This script displays the contents of the file `/etc/passwd`.
#This script should only display:
    #username
    #user id
    #Home directory path for the user

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
